'use client';
import { useEffect, useRef, type ReactNode } from 'react';
import { MessageCircle, Image, Link, ArrowDown } from 'lucide-react';
export default function WelcomeMotion({children}:{children:ReactNode}) {
 const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const el=root.current;if(!el)return;const reduce=window.matchMedia('(prefers-reduced-motion: reduce)');let frame=0;let x=0,y=0;
 const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(reduce.matches){el.style.setProperty('--scroll','0');el.style.setProperty('--cursor-x','0px');el.style.setProperty('--cursor-y','0px');return;}el.style.setProperty('--scroll',String(el.scrollTop));el.style.setProperty('--cursor-x',x+'px');el.style.setProperty('--cursor-y',y+'px');const heading=el.querySelector<HTMLElement>('.reveal-heading');if(heading){const offset=heading.getBoundingClientRect().top-el.getBoundingClientRect().top;const progress=Math.max(0,Math.min(1,(el.clientHeight*.92-offset)/(el.clientHeight*.35)));heading.style.setProperty('--reveal',progress*100+'%');}});};
 const move=(e:PointerEvent)=>{if(e.pointerType!=='mouse')return;const rect=el.getBoundingClientRect();x=(e.clientX-rect.left-rect.width/2)*.035;y=(e.clientY-rect.top-rect.height/2)*.035;update();};const leave=()=>{x=0;y=0;update();};
 el.addEventListener('scroll',update,{passive:true});el.addEventListener('pointermove',move,{passive:true});el.addEventListener('pointerleave',leave);window.addEventListener('resize',update);reduce.addEventListener('change',update);update();return()=>{cancelAnimationFrame(frame);el.removeEventListener('scroll',update);el.removeEventListener('pointermove',move);el.removeEventListener('pointerleave',leave);window.removeEventListener('resize',update);reduce.removeEventListener('change',update);};},[]);
 return <div className="motion-scroll" ref={root}><div className="parallax-layer layer-one" aria-hidden="true"/><div className="parallax-layer layer-two" aria-hidden="true"/><div className="cursor-glow" aria-hidden="true"/><div className="welcome">{children}<button className="scroll-invite" onClick={()=>root.current?.querySelector('.motion-story')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}>Continue a conversa <ArrowDown size={16}/></button></div><section className="motion-story"><p className="eyebrow">CADA CONVERSA TEM SEU JEITO</p><h3 className="reveal-heading">Um oi. Uma foto.<br/>Algo que lembra você.</h3><div className="stack-cards"><article className="stack-card card-one"><span className="card-number">01 / MENSAGENS</span><MessageCircle className="rotating-icon" size={48}/><h4>As palavras aproximam.</h4><p>Encontre alguém pelo @usuário e comece a conversar.</p></article><article className="stack-card card-two"><span className="card-number">02 / IMAGENS E ARQUIVOS</span><Image className="rotating-icon" size={48}/><h4>Compartilhe seu mundo.</h4><p>Uma foto do dia ou aquele arquivo que ficou de enviar. Tudo na mesma conversa.</p></article><article className="stack-card card-three"><span className="card-number">03 / LINKS</span><Link className="rotating-icon" size={48}/><h4>“Olha o que eu achei.”</h4><p>Envie um link e dê mais um motivo para a conversa continuar.</p></article></div></section></div>;
}
